DROP TABLE IF EXISTS STUDENT;
DROP TABLE IF EXISTS INSTRUMENT;
DROP TABLE IF EXISTS COMPOSITION;
DROP TABLE IF EXISTS PERFORMANCE;
DROP TABLE IF EXISTS PERFORMANCE_PARTICIPANTS;

CREATE TABLE INSTRUMENT (
       ID INT NOT NULL AUTO_INCREMENT
     , TYPE VARCHAR(15) NOT NULL
     , PRODUCER VARCHAR(30) NOT NULL
     , PROD_DATE DATE
     , PURCH_DATE DATE
     , PRIMARY KEY (ID)
);

CREATE TABLE STUDENT (
       ID INT NOT NULL AUTO_INCREMENT
     , INSTRUMENT_ID INT NOT NULL DEFAULT 0
     , FIRST_NAME VARCHAR(40) NOT NULL
     , LAST_NAME VARCHAR(40) NOT NULL
     , BIRTH_DATE DATE
     , PRIMARY KEY (ID)
     , FOREIGN KEY (INSTRUMENT_ID)
    			   REFERENCES INSTRUMENT (ID)
);

CREATE TABLE COMPOSITION (
       ID INT NOT NULL AUTO_INCREMENT
     , TITLE VARCHAR(25) NOT NULL
     , AUTHOR VARCHAR(50) NOT NULL
     , PRIMARY KEY (ID)
);

CREATE TABLE PERFORMANCE (
       ID INT NOT NULL AUTO_INCREMENT
     , COMPOSITION_ID INT NOT NULL
     , PRIMARY KEY (ID)
     , FOREIGN KEY (COMPOSITION_ID)
                    REFERENCES COMPOSITION (ID)
);

CREATE TABLE PERFORMANCE_PARTICIPANTS (
        STUDENT_ID INT NOT NULL
     ,  PERFORMANCE_ID INT NOT NULL
     ,  FOREIGN KEY (STUDENT_ID)
                    REFERENCES STUDENT (ID)
     ,  FOREIGN KEY (PERFORMANCE_ID)
                    REFERENCES PERFORMANCE (ID)
);